### ISSUE TITLE
Find out how we can, in KiCad, create a drone shaped PCB and how we send that to PCBWay. Also find out how much the cost increases for making a non-rectangular PCB

### ISSUE THREAD

**Issue by markusheimerl** [heimerlrobotics/board#1]
Creating a prototype nano drone shaped pcb should be included in this task. Communcation to PCBWay seems also necessary. (I installed the PCBWay Plugin in KiCad, works great!)

**Comment by markusheimerl** [comment]
I have a conceptual solution.

I bought these batteries:
https://www.ebay.de/itm/255510046348?var=555462939810

They come with a JST-PH 2.0 plug. On Mouser I downloaded the KiCad Symbols for the JST-PH 2-pin jack: https://www.mouser.de/ProductDetail/Adafruit/1769?qs=GURawfaeGuBbgoGtf2XstA%3D%3D

Which means I add these symbols to the schematic and pcb in KiCad. I upload the exported gerber files and bom from kicad to pcbway.

PCBWays turnkey service should easily be able to source the jack.

**Comment by JunaidAhmad92** [comment]
There is not a lot of difference in the price due to the shape of the PCB so it's up to us how we want the PCB to look.

**Comment by markusheimerl** [comment]
so according to junaid this should be no problem it seems
